In [1]:
import h5py
import numpy as np

In [2]:
train_path = r"E:\Dai hoc\2526I\dacn\flow-matching\data\traintest_hcd.hdf5"
test_path = r"E:\Dai hoc\2526I\dacn\flow-matching\data\holdout_hcd.hdf5"

In [30]:

with h5py.File(train_path, "r") as f:
    print("Keys:", list(f.keys()))

    train_seqs = f["sequence_integer"][:]
    train_charges = f["precursor_charge_onehot"][:]

with h5py.File(test_path, "r") as f:
    print("Keys:", list(f.keys()))

    test_seqs = f["sequence_integer"][:]    
    test_charges = f["precursor_charge_onehot"][:]
    

Keys: ['collision_energy', 'collision_energy_aligned', 'collision_energy_aligned_normed', 'intensities_raw', 'masses_pred', 'masses_raw', 'method', 'precursor_charge_onehot', 'rawfile', 'reverse', 'scan_number', 'score', 'sequence_integer', 'sequence_onehot']
Keys: ['collision_energy', 'collision_energy_aligned', 'collision_energy_aligned_normed', 'intensities_raw', 'masses_pred', 'masses_raw', 'method', 'precursor_charge_onehot', 'rawfile', 'reverse', 'scan_number', 'score', 'sequence_integer']


In [31]:
train_charges = np.argmax(train_charges, axis=1) + 1
test_charges = np.argmax(test_charges, axis=1) + 1

## Train/test ratio

In [51]:
len(train_seqs) / len(test_seqs)

8.999997348236246

### Check for duplicate precursors

In [34]:
train_set = {tuple(seq): i for i, seq in enumerate(train_seqs)}

In [50]:
test_charges[0:9]

array([2, 3, 2, 2, 2, 3, 2, 2, 2])

In [35]:
duplicate = []
for i, seq in enumerate(test_seqs):
    seq_t = tuple(seq)
    if seq_t in train_set.keys():
        j = train_set[seq_t]
        if train_charges[j] == test_charges[i]:
            duplicate.append((i, j))

In [40]:
duplicate

[(0, 5890740),
 (2, 5890740),
 (3, 5890740),
 (4, 5890740),
 (6, 5890740),
 (7, 5890740),
 (8, 5890740)]

In [46]:
test_seqs[9], test_charges[9]

(array([ 8, 10, 21,  9, 16, 18, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 np.int64(2))

In [43]:
train_seqs[5890740], train_charges[5890740]

(array([20, 18, 18, 18, 20,  5, 15,  4,  8,  3, 17,  9,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 np.int64(2))